# python
#
# VERSION               0.0.1

FROM     alamilla/base
MAINTAINER Andres F. Lamilla, "alamilla@gmail.com"

# se actualiza la base de datos de apt
RUN apt-get update -qq #16/07/2014

# instalacion de los paqutes necesarios
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python python-pip
